sudo: required
services:
  - docker

before_install:
  - docker build -t chuckmdonaldson/docker-frontend-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chuckmdonaldson/docker-frontend-react npm run test